version: '3.8'

services:
  server:
    build:
      context: ./jobbergate-api
      dockerfile: Dockerfile-dev
      args:
        - PYPI_PASSWORD=${PYPI_PASSWORD}
    networks:
      - jobbergate-net
    volumes:
      - ./jobbergate-api/jobbergate_api:/app/jobbergate_api
    command: poetry run dev-tools dev-server --port=8000
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_USER=${DATABASE_USER:-omnivector}
      - DATABASE_PSWD=${DATABASE_PSWD:-local-pswd}
      - DATABASE_NAME=${DATABASE_NAME:-jobbergate}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL:-http://minio:9000}
      - S3_BUCKET_NAME=${S3_ENDPOINT_URL:-jobbergate-resources}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-FAKE_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-FAKE_SECRET_ACCESS_KEY}
      - ARMASEC_DOMAIN=${AUTH0_DOMAIN}
      - ARMASEC_AUDIENCE=${AUTH0_AUDIENCE}
      - ARMASEC_DEBUG=${ARMASEC_DEBUG}
    ports:
      - 8000:8000

  db:
    image: postgres
    restart: always
    networks:
      - jobbergate-net
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${NEXTGEN_DATABASE_PSWD:-local-pswd}
      - POSTGRES_USER=${NEXTGEN_DATABASE_USER:-omnivector}
      - POSTGRES_DB=${NEXTGEN_DATABASE_NAME:-jobbergate}
    ports:
      - 5432:5432

  test-db:
    image: postgres
    restart: always
    networks:
      - jobbergate-net
    tmpfs:
      - /var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=${NEXTGEN_DATABASE_PSWD:-test-pswd}
      - POSTGRES_USER=${NEXTGEN_DATABASE_USER:-test}
      - POSTGRES_DB=${NEXTGEN_DATABASE_NAME:-test-jobbergate}
    ports:
      - 5433:5432

  minio:
    image: minio/minio
    networks:
      - jobbergate-net
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID:-FAKE_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY:-FAKE_SECRET_ACCESS_KEY}
    command: ["server", "--compat", "--console-address", ':9001', "/data"]

  adminer:
    image: adminer
    networks:
      - jobbergate-net
    restart: always
    ports:
      - 8080:8080

volumes:
    postgres_data:
    minio_data:

networks:
  jobbergate-net:
    driver: bridge
