name: 'Test'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - uses: Gr1N/setup-poetry@v7
      - name: "run full suite of tests"
        env:
          POETRY_HTTP_BASIC_PYPICOUD_USERNAME: admin
          POETRY_HTTP_BASIC_PYPICOUD_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: make qa
